"""Add last session time to member

Revision ID: 349106f90cb3
Revises: c6e00a6adfab
Create Date: 2025-05-10 16:09:14.491073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349106f90cb3'
down_revision: Union[str, None] = 'c6e00a6adfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('time_since_last_session', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'time_since_last_session')
    # ### end Alembic commands ###
