"""Add member blacklist bool

Revision ID: 85bfff5ba6a6
Revises: a9f202a7076a
Create Date: 2025-06-01 18:57:21.551287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85bfff5ba6a6"
down_revision: Union[str, None] = "a9f202a7076a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members", sa.Column("blacklisted", sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "blacklisted")
    # ### end Alembic commands ###
