"""Update sources constraint

Revision ID: a9f202a7076a
Revises: 349106f90cb3
Create Date: 2025-05-29 14:25:34.788139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9f202a7076a"
down_revision: Union[str, None] = "349106f90cb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("voices", "voices_old")

    op.create_table(
        "voices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.CheckConstraint("source IN ('local', 'elevenlabs', 'chatterbox')", name="chk_source_valid_val"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("uid"),
    )

    op.execute(
        """
        INSERT INTO voices (id, name, uid, source)
        SELECT id, name, uid, source FROM voices_old
    """
    )

    op.drop_table("voices_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM voices WHERE source = 'chatterbox'
    """
    )
    op.rename_table("voices", "voices_old")
    op.create_table(
        "voices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.CheckConstraint("source IN ('local', 'elevenlabs')", name="chk_source_valid_val"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("uid"),
    )

    op.execute(
        """
        INSERT INTO voices (id, name, uid, source)
        SELECT id, name, uid, source FROM voices_old
    """
    )

    op.drop_table("voices_old")
    # ### end Alembic commands ###
