"""Create a baseline migrations

Revision ID: c6e00a6adfab
Revises: 
Create Date: 2025-02-02 14:54:50.838161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e00a6adfab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.CheckConstraint("source IN ('local', 'elevenlabs')", name='chk_source_valid_val'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pfp_url', sa.String(), nullable=False),
    sa.Column('num_sessions', sa.Integer(), nullable=False),
    sa.Column('preferred_tts_uid', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['preferred_tts_uid'], ['voices.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('voices')
    # ### end Alembic commands ###
